name: CI
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  start-metis-pipeline:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs some way to start the metis pipeline
      - name: Run a one-line script
        run: Start-MetisRun ...
        
  finish-metis-pipeliine:
    runs-on: ubuntu-latest
    # this environment requires approval, if the metis pipeline sends a POST to 
    # https://api.github.com/repos/OWNER/REPO/actions/runs/RUN_ID/approve it will execute the steps below
    environment: development
    needs: [start-metis-pipeline]
    
    steps:
      - name: Check metis result
        run: Verify-MetisRun

      
      
    
      
